### ISSUE TITLE
Improve jqrs thresholding by running it on 1-min segments

### ISSUE THREAD

**Issue by fernandoandreotti** [fernandoandreotti/fecgsyn#37]
Fix this on `QRSmincompare.m`, which at the time processing the whole recordings (for FECGSYNDB = 5min)

**Comment by fernandoandreotti** [comment]
Fixed.

**Comment by jbehar** [comment]
;)

2016-09-02 15:18 GMT+03:00 Fernando Andreotti <notifications@github.com>:
