### ISSUE TITLE
Update Naive Bayes to use fitcnb from Matlab

### ISSUE THREAD

**Issue by fernandoandreotti** [fernandoandreotti/fecgsyn#39]
> Warning: NaiveBayes will be removed in a future release. Use the predict method of an object returned by fitcnb instead. 
> > In NaiveBayes/posterior (line 46)
>   In classreg.learning.internal.DisallowVectorOps/subsref (line 21) 
> Warning: NaiveBayes will be removed in a future release. Use the predict method of an object returned by fitcnb instead. 
> > In NaiveBayes/posterior (line 46)
>   In classreg.learning.internal.DisallowVectorOps/subsref (line 21) 
> Warning: NaiveBayes will be removed in a future release. Use the predict method of an object returned by fitcnb instead. 
> > In NaiveBayes/posterior (line 46)
>   In classreg.learning.internal.DisallowVectorOps/subsref (line 21)

**Comment by fernandoandreotti** [comment]
Retrained Naive Bayes model to use `fitcnb()`, see comit https://github.com/fernandoandreotti/fecgsyn/commit/02c56a3aba6d8ea4a3a03d0a5572f5082f5ea342

**Comment by KingfaLuis** [comment]
错误使用 NaiveBayes/posterior (line 46)
NaiveBayes will be removed in a future release. Use the predict method of an object returned by fitcnb instead.

**Comment by fernandoandreotti** [comment]
Dear @KingfaLuis can you specify when you encountered this warning?
