### ISSUE TITLE
Documentation is unavailable 

### ISSUE THREAD

**Issue by wildwind0** [fernandoandreotti/fecgsyn#40]
Documentation available at: www.fecgsyn.com
I can't access the website, please check out.

**Comment by fernandoandreotti** [comment]
Hi, I just checked it is working for me. Could you check again?
Alternatively you can try to access http://fernandoandreotti.github.io/fecgsyn/

**Comment by wildwind0** [comment]
Sorry, I still can't access these links. I also asked my friends to have a try, and they had the same problem.

**Comment by fernandoandreotti** [comment]
Is the problem persisting? What error are you seeing?
I can access both without any problems.

**Comment by wildwind0** [comment]
Now, I can access http://fernandoandreotti.github.io/fecgsyn/, but www.fecgsyn.com is not accessible.
Maybe it is a problem with my Internet. Thank you for your contribution to the field of fetal ECG research. I appreciate your work!!

**Comment by fernandoandreotti** [comment]
Awesome! I am glad to hear it :)
