### ISSUE TITLE
add_noisedipole with octave

### ISSUE THREAD

**Issue by ericqu** [fernandoandreotti/fecgsyn#45]
While using octave, and following the section "Initial NI-FECG simulation example" from the getting started webpage I encountered an error stating that the pca function is missing in the statistics package.

I noted that there is a "princomp" function in the package, and changed the line 166 from 
`[~,pc] = pca(noise_ar);`
to 
`[~,pc] = princomp(noise_ar);`

It resolved the issue, however I am new to octave/matlab, so I am not 100% sure that the function are interchangeable. Could someone kindly indicate that this change is making sense?

**Comment by fernandoandreotti** [comment]
Hi @ericqu, Matlab has removed `princomp` function on 2019a. Instead it suggests using `pca`. Sorry for this conflict, I have pushed the following PR https://github.com/fernandoandreotti/fecgsyn/pull/47 and will check if it runs smoothly.

**Comment by ericqu** [comment]
thanks
