### ISSUE TITLE
How to generate signals from different people?

### ISSUE THREAD

**Issue by ElectricSquirrel** [fernandoandreotti/fecgsyn#48]
Hi, I wonder how to generate signals from different people?
There are 10 pregnant women mentioned in the introduction of fecgdb data set. How are they generated? What's the difference?

**Comment by fernandoandreotti** [comment]
Hi sorry for the delay. The VCGs were derived from https://physionet.org/content/ptbdb/1.0.0/
We described this in https://iopscience.iop.org/article/10.1088/0967-3334/35/8/1537/meta

After generating VCGs you derive Gaussian approximations of those, it should be easy enough to obtain more.
