### ISSUE TITLE
out.mixture in run_ecg_generator

### ISSUE THREAD

**Issue by ericqu** [fernandoandreotti/fecgsyn#49]
This is more question (or a problem with the documentation) than an issue but I wasn't sure how else to raise my question.
In the function run_ecg_generator several outputs are generated. Among them out.mixture defined as "generated ecg mixture [NB_EL x param.n matrix]". 

- I am not sure what NB_EL represents, is it the number of electrodes capturing signals? 
- Is it the same for the mother ecg and foetus ecg?
- Is there is a special meaning for the first one (it looks a bit different to the others)?

**Comment by fernandoandreotti** [comment]
Hi @ericqu this is a good place for question, don't be shy to ask.
- Yes, NB_EL = number of modelled electrodes
- Yes, electrodes are just observation points on the cylinder. 
- If you see the function run_ecg_generator, the default position of these electrodes are described in  [here](https://github.com/fernandoandreotti/fecgsyn/blob/5504b0477e373f5209a260f0604c3203f7e0f814/subfunctions/data-generation/run_ecg_generator.m#L169). There should be 32 abdominal electrodes and 2 maternal ECG reference ones. Am I right?

**Comment by ericqu** [comment]
Thank you @fernandoandreotti  this answer my question perfectly!
