### ISSUE TITLE
where's the data for this article?

### ISSUE THREAD

**Issue by appleyuchi** [fernandoandreotti/fecgsyn#50]
could you tell me where the data for this article:

\<Non-invasive Fetal ECG Signal Quality
Assessment for Multichannel
Heart Rate Estimation\>

`A total of n = 259 mul-
tichannel recordings from 107 singleton pregnancies (diverse
pathophysiological states and gestational weeks ranging from
17 to 39 weeks) were collected.`

Thanks for your help!

**Comment by fernandoandreotti** [comment]
Unfortunately this data refers to a real private dataset.
