### ISSUE TITLE
Generating new Dataset- problem with saving ouputs

### ISSUE THREAD

**Issue by rraccah** [fernandoandreotti/fecgsyn#51]
Hi, 
I've run the following code in order to generate new data ( as shown in your examples):

param.fs = 1000; % data generation at 1kHz
param.n = 15*param.fs;
param.SNRfm = -3; % fetal maternal SNR
param.SNRmn = 8; % maternal to noise SNR
param.ntype = {'MA'}; % adding muscular artifact type noise
param.noise_fct = {1}; % noise at constant SNR level
debug = 5; % debug level (5 = max number of plots generated)
out = run_ecg_generator(param,debug);
FECGSYN_plotmix(out) % plots random channels of one of the created datasets

In the examples it's written that "The code will produce simulation files". I specified the desires path on the Matlab root with cd savedir but i don't get any simulation files. 
Could anyone help me out?
Thank you in advance, 

Rebecca

**Comment by fernandoandreotti** [comment]
Hi Rebecca,

I think the instructions were misleading, it does generate the `out` variable with simulations, but it does not save it anywhere by default. Please have a look at the documentation in of `run_ecg_generator()` https://github.com/fernandoandreotti/fecgsyn/blob/master/subfunctions/data-generation/run_ecg_generator.m

Best regards,

Fernando

**Comment by rraccah** [comment]
Thank you very much Fernando!

Sincerely,
Rebecca

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
